Malikinden/Malikinden/Controllers/AracController.cs
using BusinessLogic.Abstract;
using BusinessLogic.Concrete;
using Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Malikinden.Controllers
{
    public class AracController : Controller
    {
        private readonly ICarService _Aracservice;
        private readonly IService<Musteri> _Musteriservice;
        private readonly IService<Talep> _Talepservice;

        public AracController(ICarService aracservice, IService<Musteri> musteriservice, IService<Talep> talepiservice)
        {
            _Aracservice = aracservice;
            _Musteriservice = musteriservice;
            _Talepservice = talepiservice;
        }

        public async Task<IActionResult> IndexAsync(int id)
        {
            var model = await _Aracservice.GetCustomCar(id);
            ViewBag.AracId = new SelectList(await _Aracservice.GetAllAsync(), "Id", "Model");
            ViewBag.TalepId = new SelectList(await _Talepservice.GetAllAsync(), "Id", "Tur");
            return View(model);
        }

        [Route("tum-araclarimiz")]
		public async Task<IActionResult> List()
		{
			var model = await _Aracservice.GetCustomCarList(c=>c.SatistaMi);
			return View(model);
		}
        public async Task<IActionResult> Ara(string q)
        {
            var model = await _Aracservice.GetCustomCarList(c => c.SatistaMi && c.Marka.Adi.Contains(q) || c.KasaTipi.Contains(q));
            return View(model);
        }
        public async Task<ActionResult> Musteri()
        {
           
            ViewBag.TalepId = new SelectList(await _Talepservice.GetAllAsync(), "Id", "Tur");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Musteri(Musteri musteri)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    TempData["basarili"] = "Bilgi Gonderildi";
                    await _Musteriservice.AddAsync(musteri);
                    await _Musteriservice.SaveAsync();
                    return Redirect("/Arac/Index/" + musteri.AracId);

                }
                catch
                {
                    TempData["basarisiz"] = "Eksik Ya da Gecersiz Islem";
                }
            }
            ViewBag.AracId = new SelectList(await _Aracservice.GetAllAsync(), "Id", "Model");
            ViewBag.TalepId = new SelectList(await _Talepservice.GetAllAsync(), "Id", "Tur");
            return View(musteri);
        
        }
    }
}

Malikinden/Malikinden/Controllers/FavoritesController.cs
using BusinessLogic.Abstract;
using Entity;
using Malikinden.ExtensionMethods;
using Microsoft.AspNetCore.Mvc;

namespace Malikinden.Controllers
{
    public class FavoritesController : Controller
    {
        private readonly ICarService _Aracservice;
        public FavoritesController(ICarService aracservice)
        {
            _Aracservice = aracservice;
        }
        public IActionResult Index()
        {
            var favoriler = GetFavorites();
            return View(favoriler);
        }
        private List<Arac>GetFavorites()
        {
            List<Arac>? araclar = new();
            araclar = HttpContext.Session.GetJson<List<Arac>>
                ("GetFavorites");
            return araclar ?? new List<Arac>();
        }
        public IActionResult Add(int aracId)
        {
            try
            {
                var arac = _Aracservice.Find(aracId);
                var favoriler = GetFavorites();
                if (favoriler != null && !favoriler.Any(a => a.Id == aracId))
                {
                    favoriler.Add(arac);
                    HttpContext.Session.SetJson("GetFavorites", favoriler);
                }
            }
            catch (Exception)
            {
                TempData["Message"] = "<div class='alert alert-danger'>HATA OLUŞTU</div>";
               
            }
           
            return RedirectToAction("Index");
        }
        public IActionResult Remove(int aracId)
        {
            try
            {
                var arac = _Aracservice.Find(aracId);
                var favoriler = GetFavorites();
                if (favoriler != null && favoriler.Any(a => a.Id == aracId))
                {
                    favoriler.RemoveAll(a => a.Id == aracId);
                    HttpContext.Session.SetJson("GetFavorites", favoriler);
                }
            }
            catch (Exception)
            {
                TempData["Message"] = "<div class='alert alert-danger'>HATA OLUŞTU</div>";

            }

            return RedirectToAction("Index");
        }
    }
}

Malikinden/Malikinden/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Malikinden</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="/admin/css/styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/vendor/sweetalert/sweetalert2.css" asp-append-version="true" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ŞAHİN Galeri</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Home" asp-action="Privacy">Hakkımızda</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Arac" asp-action="List">Tüm Araçlarımız</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Iletisim">Iletisim</a>
                        </li>
                        
                    </ul>
                </div>
                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" asp-action="Ara" asp-controller="Arac" method="get">
                    <input name="q" type="search" class="form-control form-control-dark text-bg-dark" placeholder="Ara..." aria-label="Search">
                </form>
               
                <div class="text-end">
                    @if (Context.User.Identity.IsAuthenticated)
                    {

                        <a asp-controller="Favorites" asp-action="Index" class="btn btn-warning ">Favorilerim</a>
                        <a asp-controller="Account" asp-action="Logout" class="btn btn-primary">Oturumu Kapat</a>
                    }
                    else
                    {
                        <a asp-controller="Account" asp-action="Login" class="btn btn-warning ">Giriş</a>
                        <a asp-controller="Account" asp-action="Register" class="btn btn-primary">Kayıt Ol</a>
                    }
                    
                </div>
            </div>
        </nav>
    </header>
   
            @RenderBody()
       

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Malikinden -Emrah ŞAHİN tarafından Ahmet Yesevi Üniversitesi Proje Dersi için Tasarlanmıştır. <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/vendor/sweetalert/sweetalert2.all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>